[package]
name = "matcher"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
regex = { workspace = true }
test-case = { workspace = true }
