[workspace]
resolver = "3"
members = ["regex", "greppy"]

[workspace.package]
version = "0.1.0"
authors = ["Gustavo Batistela @gustavobat"]
edition = "2024"
rust-version = "1.88"

[workspace.dependencies]
regex = { path = "regex" }