[package]
name = "greppy"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
regex = { workspace = true }
matcher = { workspace = true }
clap = { workspace = true }
